### ISSUE TITLE
Plugins master catalog error status

### ISSUE THREAD

**Issue by bdbcat** [OpenCPN/plugins#144] opened 2020-06-18 01:50 UTC
All...
After significant editing, the master catalog still exhibits some errors found by #make validate" step.

```
dsr@dsr-HPE-580t:~/Projects/plugins$ make validate
xmllint  --schema ocpn-plugins.xsd  ocpn-plugins.xml --noout
ocpn-plugins.xml:1647: element target: Schemas validity error : Element 'target': [facet 'enumeration'] The value 'darwin-x86_64' is not an element of the set {'darwin', 'debian-armhf', 'debian-x86_64', 'flatpak', 'flatpak-x86_64', 'mingw', 'msvc', 'raspbian-armhf', 'ubuntu-arm64', 'ubuntu-gtk3-arm64', 'ubuntu-gtk3-x86_64', 'ubuntu-x86_64'}.
ocpn-plugins.xml:1647: element target: Schemas validity error : Element 'target': 'darwin-x86_64' is not a valid value of the local atomic type.
ocpn-plugins.xml:2753: element target: Schemas validity error : Element 'target': [facet 'enumeration'] The value 'debian-gtk3-x86_64' is not an element of the set {'darwin', 'debian-armhf', 'debian-x86_64', 'flatpak', 'flatpak-x86_64', 'mingw', 'msvc', 'raspbian-armhf', 'ubuntu-arm64', 'ubuntu-gtk3-arm64', 'ubuntu-gtk3-x86_64', 'ubuntu-x86_64'}.
ocpn-plugins.xml:2753: element target: Schemas validity error : Element 'target': 'debian-gtk3-x86_64' is not a valid value of the local atomic type.
ocpn-plugins.xml fails to validate
Makefile:24: recipe for target 'validate' failed
make: *** [validate] Error 3

```
I see 2 basic errors when ocpn-plugins.xml is validated against ocpn-plugins.xsd.
One in "windvane", and one in "squiddio"

Please submit corrective PRs when convenient.
Thanks.

**Comment by jongough** [comment] 2020-06-18 09:00
I have submitted the new windvane files and hopefully it should work now for darwin I have yet to remove the fedora build, but I am getting there.

**Comment by bdbcat** [comment] 2020-06-18 12:42
jon...
I still see Fedora in windvane

**Comment by jongough** [comment] 2020-06-18 21:11
[https://github.com/OpenCPN/plugins/issues/144#issuecomment-645883378](https://github.com/OpenCPN/plugins/issues/144#issuecomment-645883378), I know, but I was going through the process. I will now use this to check on auto-generate of the ocpn-plugins.xml file.

**Comment by rgleason** [comment] 2020-07-21 10:00
Since Mauro has made his first squiddio PR to plugins and it has been accepted, he would be the logical one to fix the error.
I will alert him to this post.  This is the first I saw this.

**Comment by mauroc** [comment] 2020-07-21 23:05
@rgleason I ran` make validate` on the latest version of the catalog and could not reproduce the error above. The only error generated was at row 4220 which  appears to affect windvane, not squiddio. Please let me know if I am missing something

**Comment by mauroc** [comment] 2020-07-21 23:18
correction: the affected row number is 2745 in the current version of ocpn-plugins.xml

**Comment by rgleason** [comment] 2020-07-22 00:03
Yes, a search on "fedora" yields just windvane and Jon does know about that.  Thanks. No need to do anything I guess.

```
 <plugin version="1">
    <name> windvane </name>
    <version> 1.0.17.2 </version>
    <release> 2 </release>
    <summary> Plugin to provide windvane like autopilot </summary>
    <api-version> 1.16 </api-version>
    <open-source> yes </open-source>
    <author> Jon Gough </author>
    <source> https://github.com/jongough/windvane_pi </source>
    <description>
Windvane Autopilot is designed to use the wind instruments and autopilot on board the yatch to act like a standard windvane autopilot and allow the yatch to follow the wind.
</description>
    <target>fedora-x86_64</target>
    <target-version>29</target-version>
    <target-arch>x86_64</target-arch>
    <tarball-url>
https://dl.cloudsmith.io/public/jon-gough/windvane_pi-prod/raw/names/windvane_pi-1.0.17.2-fedora-x86_64-29-fedora-tarball/versions/v1.0.17.2/windvane_pi-1.0.17.2-fedora-x86_64-29-fedora.tar.gz
</tarball-url>
    <info-url> https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:plugins:sailing:windvane </info-url>
  </plugin>
```

**Comment by leamas** [comment] 2021-06-20 09:09
One year later... still an issue?

**Comment by rgleason** [comment] 2023-05-02 11:20
Can someone authorized, close this? @bdbcat  @leamas @nohal

**Comment by leamas** [comment] 2023-08-04 12:22
@bdbcat  ^

**Closed** 2023-08-04 14:45 UTC
