### ISSUE TITLE
Android: Watchdog PI geometry and functions

### ISSUE THREAD

**Issue by nocheinpeter** [OpenCPN/plugins#960] opened 2023-08-09 13:56 UTC
On Android 11 (Samsung Galaxy Tab A) the watchdog pi v2.4.61.0 has following problems:

1. settings tab plugins: setting for wd pi open "about" window, which cannot be closed; OpenCPN app then must be killed
2. icon at menu bar is only a black rectangle 
3. wd pi window opened via menu bar hides menu bar's hamburger icon: changing geometry setting in opencpn.conf file (Settings/Watchdog: DialogPosX=100, ..Y=20) fixes the improber position
4. wd pi window is to small (Settings/Watchdog: DialogWidth=500, ..Height=300) fixes small window
5. wd window is missing alarms for depth, landfall, boundary, rudder, pypilot; notably depth alarm will be very helpful
6. context menu on alarms is missing (e.g. to edit an alarm)

**Comment by rgleason** [comment] 2023-09-03 10:20
Please try the new version. It has been updated.
Read the manual. The opening window is small until you right click and add and setup alarms.
Several alarms have been updated and improved.

**Comment by nocheinpeter** [comment] 2023-09-04 14:57
Using v2.4.70.0
Item 6. is fixed, remaining items still the same.

**Comment by rgleason** [comment] 2023-09-04 15:48
1. Preferences Tab  "About Author" goes to a web page https://seandepagnier.users.sourceforge.net/
 On windows it works properly. On android the screen gets frozen and you have to close all apps and restart.
Don't use About Author for now.

2. Icon at menubar is black.  On windows the icon shows properly, don't know what the problem is with Android at this point.
Yes, I notice this too. Maybe Android does not support svg?  or perhaps we did not include svg properly for android?

3. Agreed,  for android the opening menu obscures the Hamburger in the Toolbar, it should be offset.

4.  Agreed. Also the window is very very hard to drag open.  wd pi window is to small (Settings/Watchdog: DialogWidth=500, ..Height=300) fixes small window

5. Agreed wd window is missing alarms for depth, landfall, boundary, rudder, pypilot; notably depth alarm will be very helpful.
Only Anchor, Course, Speed, Wind, Weather, Deadman, Nmea Data are available. Why?

7. Agreed. Fixed. context menu on alarms is missing (e.g. to edit an alarm)

**Comment by rgleason** [comment] 2023-09-04 16:21
[nocheinpeter](https://github.com/nocheinpeter) This is all in the wrong place.
Use watchdog  Issues here on sean's repo  https://github.com/seandepagnier/watchdog_pi/issues/130
[nocheinpeter](https://github.com/nocheinpeter) Please close this Issue now and use the new location

**Closed** 2023-09-04 16:53 UTC
