### ISSUE TITLE
Many Android Build Issues have this error

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#912] opened 2023-06-13 20:45 UTC
```
CPack: Create package
CMake Error at /usr/share/cmake-3.16/Modules/Internal/CPack/CPackDeb.cmake:221 (message):
  Unable to determine Build ID for ./lib/opencpn/libaisradar_pi.so
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/Internal/CPack/CPackDeb.cmake:763 (cpack_deb_prepare_package_vars)


CPack Error: Error while execution CPackDeb.cmake
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: aisradar
make: *** [Makefile:133: package] Error 1
```

aisradar is just one example
https://app.circleci.com/pipelines/github/rgleason/AISradar_pi/98/workflows/f3e0bf7e-268d-4839-bebc-14b2557cb152/jobs/1330

NOTE this was further ahead in the file

```
Get:19 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
Fetched 13.9 MB in 1s (9,344 kB/s)
Reading package lists...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.cloud.google.com/apt cloud-sdk InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
W: Failed to fetch https://packages.cloud.google.com/apt/dists/cloud-sdk/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
W: Some index files failed to download. They have been ignored, or old ones used instead.
+ sudo apt-get -y install git cmake gettext unzip

```

**Comment by leamas** [comment] 2023-08-04 12:09
This is a classical error caused by a  google repo update. In this particular case we have the following in the shipdriver template:
```
# Handle possible outdated key for google packages, see #487
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | sudo apt-key add -

```

See also https://github.com/Rasbats/shipdriver_pi/issues/487. And please close this issue which is not about the catalog and related tools.

**Comment by bdbcat** [comment] 2023-08-04 14:42
Simpler explanation:
There is no such think as a .deb package build for Android.  We need only the .TGZ package.
This is fixed in my recent patches to AISRadar.

**Comment by leamas** [comment] 2023-08-04 14:53
@bdbcat: Error above is not about  building a deb package, it's about downloading deps which are needed also when building the tgz tarball.

**Comment by bdbcat** [comment] 2023-08-04 15:11
Several errors here.  
I think this particular issue is closable now, even if it needs to resurface as a specific plugin bug later.

**Closed** 2023-08-04 20:43 UTC
